### PR TITLE
Modernize addon

### PR DESCRIPTION
**Pull request by charlesfries**
- Octanify
- Upgrade Ember to v3.28
- Convert to native classes
- Fix examples

9/13/21

Did some final cleanup today, should be good to go

### CODE REVIEW

**Review by ncoquelet — COMMENTED** [review]
I don't explore all stuff in details, for exemple the test part, but it's a strong PR, especially with the release of Ember 4.
Does the author continue to maintain this plugin ?

**Comment by pauln** [comment]
Sorry for the slow response - I haven't had much time to focus on this project for a while.  At first glance, this looks good thanks - I'll take a closer look and hopefully get this merged before too much longer.

**Comment by pauln** [comment]
It's really just down to time, sorry - too busy to get it done during work hours, and too much else to do outside work hours... but I'll get to this soon.  The linting changes aren't a problem - per my previous comment, this looks good at first glance; I just need to have a slightly deeper look and do some testing.

**Comment by ncoquelet** [comment]
👍

**Comment by pauln** [comment]
v0.6.0 released - thanks again for your contribution @charlesfries!

**Pull request merged**
